name: quotable
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  go_router: ^14.2.7
  icons_launcher: ^2.1.7
  internet_connection_checker: ^2.0.0
  intl: ^0.19.0
  objectbox: ^4.0.1
  objectbox_flutter_libs: ^4.0.1
  retrofit: ^4.2.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.2.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/

flutter_native_splash:
  color: "#262626"
  image: assets/images/quote.png
  android: true
  ios: true
  android_gravity: fill
  android_12:
    color: "#262626"
    image: assets/images/quote.png

icons_launcher:
  image_path: "assets/images/quote.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
