name: quotable
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  objectbox: ^4.0.1
  objectbox_flutter_libs: ^4.0.1
  icons_launcher: ^2.1.7
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

flutter_native_splash:
  color: "#262626"
  image: assets/images/quote.png
  android: true
  ios: true
  android_gravity: fill
  android_12:
    color: "#262626"
    image: assets/images/quote.png

icons_launcher:
  image_path: "assets/images/quote.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
